### ISSUE TITLE
Top border of Dropdown Menus

### ISSUE THREAD

**Issue by LiohMoeller** [vlastavesely/raleigh-reloaded#10]
The top border of dropdown menus is not rendered correctly. It's really thick as you can see on the screenshot (marked yellowish):

![menu_top_border](https://user-images.githubusercontent.com/1267594/80962673-c0e25980-8e0d-11ea-858b-57f2577e4d94.png)

**Comment by LiohMoeller** [comment]
The fix is quite trivial:

```
menubar {
        border-image: url("assets/button.png") 2 / 2px stretch;
        padding-bottom: .3em;
}
```

**Comment by vlastavesely** [comment]
Your solution makes the bottom side of menus too wide on my system. I will play with it this evening.

**Comment by LiohMoeller** [comment]
Hmm, strange. Looks fine on my boxen.
![Raleigh_menufix](https://user-images.githubusercontent.com/1267594/81171191-43008880-8f9c-11ea-95dc-f27f097fcc81.png)

gtk+3-3.24.20

**Comment by vlastavesely** [comment]
As you may see on your screenshot, the bottom space is way bigger than the space on top. A more delicate change should be enough. I propose following fix:

```
menubar {
	border-image: url("assets/button.png") 2 / 2px stretch;
	-GtkWidget-window-dragging: true;
	padding-bottom: 1px;
}
 
```
Could you try whether it is enough to fix the problem on your system? On mine, it looks quite ok: 
![menubar](https://user-images.githubusercontent.com/22521379/81212086-a0183080-8fd4-11ea-8caa-2416f5dc0909.png)

**Comment by LiohMoeller** [comment]
Works for me as well. Thanks for taking care.

**Comment by vlastavesely** [comment]
I am playing with it a little. The final fix will be pushed in next few days.

**Comment by vlastavesely** [comment]
Fixed.

**Comment by LiohMoeller** [comment]
I am not sure what you have all changed, but with the latest Git checkout, the Checkboxes in Firefox e.g. when you select History / Clear History are not displayed anymore.

**Comment by vlastavesely** [comment]
I am wondering what do you mean. You mean in the menu? There never was a checkbox as far as I know. And in the window ‘Clear History’ I do see checkboxes (at least on Debian Stretch).

Could you send me a screenshot?

**Comment by LiohMoeller** [comment]
Sorry. It seemed to be a caching issue. After restarting the X session everything worked fine again.
