### ISSUE TITLE
LibreOffice Menubar is not displayed correctly

### ISSUE THREAD

**Issue by LiohMoeller** [vlastavesely/raleigh-reloaded#11]
On initial start of the application LibreOffice, the Menubar is not displayed correctly. All items are greyed out and when I click on one of the menu items it looks like this:

![libreoffice_menu](https://user-images.githubusercontent.com/1267594/81216314-01430280-8fdb-11ea-8651-36df8fc4c3be.png)

After switching to another application and back, the menu is again displayed correctly again.

**Comment by vlastavesely** [comment]
What version of LibreOffice do you use? I cannot reproduce the problem on my systems (Debian Stretch and Buster).

Since the virus-hysteria I am working on a place with bad internet connection so installing a virtual machine is not an option right now for me. This will need to wait :(

**Comment by LiohMoeller** [comment]
I am using LibreOffice 6.4.1.2. I have tried also different SAL_USE_VCLPLUGIN settings, without success.

**Comment by LiohMoeller** [comment]
I have now installed LibreOffice 6.2.8.2 and the issue does not occur there with export SAL_USE_VCLPLUGIN=gtk set.

**Comment by vlastavesely** [comment]
And I have 6.1.5, also without problems. Once it is possible, I will attempt to fix it somehow but I cannot promise when.

**Comment by vlastavesely** [comment]
Could update your software and check whether this issue still remains to be a problem?
If so, I need information about your software and its versions.

**Comment by vlastavesely** [comment]
Any update?

**Comment by vlastavesely** [comment]
Closing for no response. Feel free to reopen if the issue prevails.
