### ISSUE TITLE
mate-volume-control

### ISSUE THREAD

**Issue by antitoxine** [vlastavesely/raleigh-reloaded#12]
![mate-volume-control-applet-1](https://user-images.githubusercontent.com/64896914/82354281-e9b74100-9a00-11ea-8610-3d3264db03be.png)
![mate-volume-control-applet-2](https://user-images.githubusercontent.com/64896914/82354309-f045b880-9a00-11ea-87a4-93889a68706c.png)

microphone level indicator
in mate-volume-control-applet is absent
it works in  traditionalok theme

**Comment by vlastavesely** [comment]
> in mate-volume-control-applet is absent

Is it? I have already fixed this problem a few days ago (10 May 2020). Try the latest version of the theme.

**Comment by antitoxine** [comment]
it works
thank you so much

![mate-volume-control](https://user-images.githubusercontent.com/64896914/82563655-bba83d00-9b77-11ea-98ad-d5bfdc9f5e0d.png)
