### ISSUE TITLE
v1.4 release tag?

### ISSUE THREAD

**Issue by tsutsui** [vlastavesely/raleigh-reloaded#15]
Hi,
Is there any plan to release (i.e. create a tag) v1.4?

I was told and am using this Raleigh-Reloaded for the SNS client "mikutter" GTK3 version
https://social.mikutter.hachune.net/@shibafu528/107202192593598612
https://twitter.com/tsutsuii/status/1476270526511611904
and I've imported this into pkgsrc (package system for NetBSD etc.):
https://pkgsrc.se/graphics/raleigh-reloaded

In general, package systems require the release tar balls and incremental version numbers to verify distribution source files by SHA-256 etc. but 1.3 was tagged more than two years ago. There are several visible improvements since v1.3 so having a new v1.4 tag is very appreciated for me and probably other package system admins.

Thanks,

**Comment by vlastavesely** [comment]
Hello, yes I plan to make a new release very soon.

Before it is possible, I want to resolve the issue #14 . I was waiting for release of the new Firefox ESR in the Debian repositories. It finally happened so I can make it a priority. I suppose that within 14 days it could be released.

**Comment by tsutsui** [comment]
> I suppose that within 14 days it could be released.

No problem, I will update pkgsrc once v1.4 is tagged.
Thanks.

**Comment by vlastavesely** [comment]
I have just released version 1.4. At this point, it is without the styles for Firefox. Those will be released as version 1.5.
