### ISSUE TITLE
xfwm4 window title both the same gray; no distinction between active and inactive window.

### ISSUE THREAD

**Issue by dreirund** [vlastavesely/raleigh-reloaded#17]
I like to use this theme, but I have an issue with xfwm4 (XFCE window manager):

The window titlebars are both the same gray for an active and an inactive window. This does not allow to easily see which is the active window (only the bold title text is a hint). See attached screenshot. The xfwm4-theme I use by default sets a blue title bar colour for active window, but this does not work when I have the raleigh-reloaded theme active.

Can you make the theme colouring the active window differently (e.g. some blue tone)?

Regards!

---

![Xfwm4 window theme with `raleigh-reloaded` theme](https://github.com/vlastavesely/raleigh-reloaded/assets/1590519/85f16e8c-a2f9-4c3a-bf70-bf8496ca9785 "xfwm4-window-borders-with-raleigh-theme.png")

**Comment by vlastavesely** [comment]
Hi,
this is only a GTK theme, it does not contain themes for any window manager. You have to edit the xfwm4 theme you are using.

Theoretically, it is possible that the xfwm4 theme tries somehow to guess the right colour from the GTK theme but it would be very complicated for me to verify it and fix it. The easier solution is to edit the theme. It should be easy.

**Comment by dreirund** [comment]
OK, I have created a theme that tries to match the "raleigh-reloaded" colouring, and does some more compaction:

https://gitlab.com/dreieckli/xfwm4-theme-smallscreen-raleigh-compact

**Comment by vlastavesely** [comment]
Nice. As I see, it was problem of the theme as the colours are a part of the bitmaps. I am closing the issue.

Have a nice day.

**Comment by dreirund** [comment]
> Nice. As I see, it was problem of the theme as the colours are a part of the bitmaps.

I am not sure, because they were coloured before. But opening in gimp and re-saving did solve this issue, so maybe some meta-information was in the `.xpm`-files that gimp did not get right and by this creating `.xpm` files that force their colour, and before they had the "ability" to be styled, somehow?

Anyway, I have now [my theme on a repository](https://gitlab.com/dreieckli/xfwm4-theme-smallscreen-raleigh-compact), and linking also to your GTK3 application theme there.

Regards!
