### ISSUE TITLE
[GTK3+] Black background and foreground for tags in GNU IceCat (Firefox ESR).

### ISSUE THREAD

**Issue by wigust** [vlastavesely/raleigh-reloaded#4]
Hello,

Thank you for this awesome theme!

I have a problem with displaying tags in GNU IceCat (Firefox ESR).  They have black background and foreground.  Could you help me, please?

![](https://i.imgur.com/7HfJlWK.gifv)

Oleg.

**Comment by wigust** [comment]
See a demo on [Imgur](https://i.imgur.com/7HfJlWK.gifv).

**Comment by vlastavesely** [comment]
Hello, thanks for your report.
Sorry for the late response, but I am very busy these times. I am going to check it out today.
