### ISSUE TITLE
Firefox scroll buttons wrong state

### ISSUE THREAD

**Issue by andreyorst** [vlastavesely/raleigh-reloaded#5]
Hello, Thanks for the really nice theme.

I've found a small strange thing:
![firefox](https://user-images.githubusercontent.com/19470159/36784711-7b9d7e94-1c91-11e8-8a1e-119251951b29.png)
Despite the fact that we are able to scroll even with buttons, firefox shows buttons as unclicable.
Here are some other screenshots:
gtk2:
![gtk2](https://user-images.githubusercontent.com/19470159/36784736-97fc8d14-1c91-11e8-8363-21896ebdc521.png)
gtk3:
![gtk3](https://user-images.githubusercontent.com/19470159/36784744-9d7bd02e-1c91-11e8-9573-b7871e64d21c.png)
Libre-office:
![libre-office](https://user-images.githubusercontent.com/19470159/36784755-a4ac405e-1c91-11e8-9ace-81558f35d6e1.png)

I see that gtk2 and gtk3 uses the same assets, (same triangle arrow). Firefox and LibreOffice uses the same asset too, but different from gtk* one. It's not the point of the issue, maybe just a clue where to search for error.

**Comment by vlastavesely** [comment]
Hello,
sorry for the late response but I am very busy this time. I have prepared some changes that it could fix (not being pushed right now). If not fixed already, I will try today :)

**Comment by vlastavesely** [comment]
I have almost done a solution for the issue. It will be possible to make scrollbars in Firefox to look exactly the same as in other programs. But right now I am not fully satisfied with solution I've done so this will take a few days of trial.

**Comment by andreyorst** [comment]
That's great! Don't worry no one here in a hurry, so take your time. It's always about quality, not issue solution speed, you know :)
