### ISSUE TITLE
weird tab behavior

### ISSUE THREAD

**Issue by rkw-inspiron** [vlastavesely/raleigh-reloaded#7]
Hi I love your theme.

I was using it with mate 1.20 (backports) / gtk 3.22 in Debian 9 and I noticed something with the mate-terminal. If I have the theme selected (if I'm using your theme) and I switch tabs in the terminal, it was shrinking a line. The terminal (mate-terminal or gnome-terminal) shrinks if you have two tabs open and switch from one to another.

I was able to resolve it by removing the following from gtk-3.0/gtk-widgets.css:

notebook header.top tab:checked * {
	margin-top: 1px;
}

If I remove that chunk the shrinking behavior stops.

I don't know if your theme is even supposed to support 3.22 gtk (the description only says 3.20) so I'm not sure if this is something you'd want to look at or not but if so, here it is!

Thank you for your time and have a great day

bad
![bad](https://user-images.githubusercontent.com/45373497/49304381-2f451e80-f49a-11e8-88d7-52bfd8a23c69.gif)

good
![good](https://user-images.githubusercontent.com/45373497/49304389-3835f000-f49a-11e8-9baf-16a1bf5101d5.gif)

**Comment by vlastavesely** [comment]
Hi,
I will try to simulate the problem on my system in next few days and fix it :)

**Comment by vlastavesely** [comment]
Should be fixed now.

**Comment by rkw-inspiron** [comment]
Thank you, it works!
