### ISSUE TITLE
Tiny icons in XFCE Notification area

### ISSUE THREAD

**Issue by Spudd86** [vlastavesely/raleigh-reloaded#8]
The icons in the XFCE Notification Area are way smaller than they should be.

Running xfce panel 4.14.3 and gtk 3.24.1

Screenshot https://imgur.com/BQ2upNwl.png

**Comment by vlastavesely** [comment]
Hi, I do not use XFCE and my VirtualBox has some troubles with installing Xubuntu so solution of this issue may take a while.

**Comment by vlastavesely** [comment]
I made attempt to fix this issue. On Xubuntu it resembles how other themes are rendering notifications. Does it fix for your case?

**Comment by vlastavesely** [comment]
Closing due lack of reaction.
